[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.2.1" }
selene = { github = "Kampfkarren/selene", version = "0.21.1" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.15.1" }
wally = { github = "UpliftGames/wally", version = "0.3.1" }
