[package]
name = "alexasterisk/studio-prefab"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
ProfileService = "surnautica/profileservice@1.0.0"
Tween = "alexinite/tween@0.1.0"
PlayerResolvable = "alexinite/player-resolvable@0.1.1"
Fusion = "alexinite/fusion@0.2.0-bleeding"
TableUtil = "alexinite/table-util@0.1.0"
