[package]
name = "alexasterisk/studio-prefab"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
ProfileService = "surnautica/profileservice@1.0.0"
Logger = "alexinite/logger@0.1.1"
Maid = "alexinite/maid@2.3.2"
PlayerResolvable = "alexinite/player-resolvable@0.2.1"
TableUtil = "alexinite/table-util@0.1.1"
Tween = "alexinite/tween@0.1.0"
PropsHelper = "alexinite/props-helper@0.1.0"
