[package]
name = "alexasterisk/studio-prefab"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.14.1"
Signal = "sleitnick/signal@1.2.1"
Promise = "evaera/promise@4.0.0"
TableUtil = "sleitnick/table-util@1.1.5"
ProfileService = "surnautica/profileservice@1.0.0"
