name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "^1.0.0"

      - name: Run Lint
        run: |
          selene src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .